---
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install golang
  ansible.builtin.include_role: 
    name: gantsign.golang

- name: Install nodejs
  ansible.builtin.include_role: 
    name: andrewrothstein.node

- name: Install hugo
  ansible.builtin.include_role: 
    name: andrewrothstein.hugo

