---
- name: Install EPEL
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
    state: latest

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install packages
  ansible.builtin.dnf:
    name: 
      - snapd
    state: latest

- name: Start and enable snapd service
  ansible.builtin.systemd_service:
    name: snapd.socket
    state: started
    enabled: true

- name: Install Hugo dependencies
  community.general.snap:
    name:
      - dart-sass

- name: Install golang
  ansible.builtin.include_role: 
    name: gantsign.golang

- name: Install nodejs
  ansible.builtin.include_role: 
    name: andrewrothstein.node

- name: Install hugo
  ansible.builtin.include_role: 
    name: andrewrothstein.hugo

